
version: '2.1'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: elastic
    environment:
      cluster.name: bills-processer
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:${DATA_DIR}
    networks:
      - es

volumes:
  esdata:
    driver: local

networks:
    es:

