version: '2.1'

services:

  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    networks:
      - es
  kafka:
    image: ches/kafka:latest
    ports:
      - 9092:9092
    links:
      - zookeeper:3.4
    environment:
      ZOOKEEPER_IP: zookeeper
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    networks:
      - es
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: elastic
    environment:
      cluster.name: bills-processer
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:${DATA_DIR}
    networks:
      - es

volumes:
  esdata:
    driver: local

networks:
    es:

